src/webswview/lkswview/portal/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

import math

import gi
from flask import Blueprint, abort, flash, request, url_for, redirect, render_template
from sqlalchemy import String, and_, cast, func
from sqlalchemy.orm import joinedload
from sqlalchemy.dialects.postgresql import ARRAY

import laniakea.typing as T
from laniakea.db import (
    ArchiveSuite,
    ArchiveConfig,
    BinaryPackage,
    SourcePackage,
    ArchiveSection,
    PackageOverride,
    ArchiveRepository,
    SoftwareComponent,
    session_scope,
)
from laniakea.archive import repo_suite_settings_for

from ..extensions import cache

gi.require_version('AppStream', '1.0')
from gi.repository import AppStream

portal = Blueprint('portal', __name__)


@portal.route('/')
def index():
    return render_template('index.html')


@portal.route('/search_pkg', methods=['GET', 'POST'])
def search_pkg():
    term = request.args.get('term')
    if not term:
        flash('The search term was invalid.')
        return redirect(url_for('portal.index'))

    with session_scope() as session:
        spkg_filters = [SourcePackage.time_deleted.is_(None), SourcePackage.name.like('%' + term + '%')]

        spkg_filter_sq = session.query(SourcePackage).filter(*spkg_filters).subquery()
        smv_sq = (
            session.query(spkg_filter_sq.c.name, func.max(spkg_filter_sq.c.version).label('max_version'))
            .group_by(spkg_filter_sq.c.name)
            .subquery('smv_sq')
        )
        src_packages = (
            session.query(SourcePackage)
            .options(joinedload(SourcePackage.repo), joinedload(SourcePackage.suites))
            .filter(*spkg_filters)
            .join(
                smv_sq,
                and_(
                    SourcePackage.name == smv_sq.c.name,
                    SourcePackage.version == smv_sq.c.max_version,
                ),
            )
            .order_by(SourcePackage.name)
            .all()
        )

        bin_packages = (
            session.query(BinaryPackage)
            .options(joinedload(BinaryPackage.repo), joinedload(BinaryPackage.suites))
            .filter(
                BinaryPackage.time_deleted.is_(None), BinaryPackage.__ts_vector__.op('@@')(func.plainto_tsquery(term))
            )
            .distinct(BinaryPackage.name, BinaryPackage.version)
        ).all()

        results_count = len(bin_packages) + len(src_packages)

        results_per_page = results_count
        page_count = math.ceil(results_count / results_per_page) if results_per_page > 0 else 1

        return render_template(
            'pkg_search_results.html',
            term=term,
            results_count=results_count,
            results_per_page=results_per_page,
            page_count=page_count,
            src_packages=src_packages,
            bin_packages=bin_packages,
        )


@portal.route('/search_sw', methods=['GET', 'POST'])
def search_software():
    term = request.args.get('term')
    if not term:
        flash('The search term was invalid.')
        return redirect(url_for('portal.index'))

    with session_scope() as session:
        q = (
            session.query(SoftwareComponent)
            .join(SoftwareComponent.pkgs_binary)
            .filter(SoftwareComponent.__ts_vector__.op('@@')(func.plainto_tsquery(term)))
            .order_by(SoftwareComponent.cid, BinaryPackage.version.desc())
            .distinct(SoftwareComponent.cid)
        )

        results_count = q.count()
        software = q.all()

        results_per_page = results_count
        page_count = math.ceil(results_count / results_per_page) if results_per_page > 0 else 1

        return render_template(
            'software_search_results.html',
            term=term,
            results_count=results_count,
            results_per_page=results_per_page,
            page_count=page_count,
            software=software,
        )


@portal.route('/repos', defaults={'repo_name': None})
@portal.route('/repo/<repo_name>')
@cache.cached(timeout=8400)
def repo_index(repo_name: T.Optional[str] = None):
    with session_scope() as session:
        if not repo_name:
            selected_repo = session.query(ArchiveRepository).join(ArchiveConfig.primary_repo).one()
        else:
            selected_repo = session.query(ArchiveRepository).filter(ArchiveRepository.name == repo_name).one_or_none()
        if not selected_repo:
            abort(404)
        repos = session.query(ArchiveRepository).order_by(ArchiveRepository.name).all()

        return render_template('repo_index.html', repos=repos, selected_repo=selected_repo)


@portal.route('/<repo_name>/<suite_name>/sections')
@cache.cached(timeout=8400)
def sections_index(repo_name, suite_name):
    with session_scope() as session:
        rss = repo_suite_settings_for(session, repo_name, suite_name, fail_if_missing=False)
        if not rss:
            abort(404)

        sections = session.query(ArchiveSection).order_by(ArchiveSection.name).all()
        return render_template('sections_index.html', repo_suite=rss, sections=sections)


@portal.route('/<repo_name>/<suite_name>/<section_name>/<int:page>')
@cache.cached(timeout=3600)
def section_view(repo_name, suite_name, section_name, page):
    with session_scope() as session:
        rss = repo_suite_settings_for(session, repo_name, suite_name, fail_if_missing=False)
        if not rss:
            abort(404)
        section = session.query(ArchiveSection).filter(ArchiveSection.name == section_name).one_or_none()
        if not section:
            abort(404)

        pkgs_per_page = 50
        pkg_query = (
            session.query(BinaryPackage)
            .join(
                PackageOverride,
                and_(
                    PackageOverride.repo_id == rss.repo_id,
                    PackageOverride.suite_id == rss.suite_id,
                    PackageOverride.pkg_name == BinaryPackage.name,
                ),
            )
            .filter(BinaryPackage.repo_id == rss.repo_id)
            .filter(BinaryPackage.suites.any(ArchiveSuite.id == rss.suite_id))
            .filter(PackageOverride.section.has(id=section.id))
            .order_by(BinaryPackage.name.asc(), BinaryPackage.version.desc())
            .distinct(BinaryPackage.name)
        )
        pkgs_total = pkg_query.count()
        page_count = math.ceil(pkgs_total / pkgs_per_page)

        packages = (
            pkg_query.options(joinedload(BinaryPackage.component))
            .slice((page - 1) * pkgs_per_page, page * pkgs_per_page)
            .all()
        )

        return render_template(
            'section_view.html',
            section=section,
            repo_suite=rss,
            packages=packages,
            pkgs_per_page=pkgs_per_page,
            pkgs_total=pkgs_total,
            current_page=page,
            page_count=page_count,
        )


# cached app category dictionary
_app_categories = None


def get_app_categories():
    '''
    Retrieve a cached dict of software categories.
    '''
    global _app_categories
    if _app_categories:
        return _app_categories

    cats = {}
    ascats = AppStream.get_default_categories(False)
    for c in ascats:
        cats[c.get_id()] = c
    _app_categories = cats
    return cats


@portal.route('/categories')
@cache.cached(timeout=8400)
def categories_index():
    categories = get_app_categories()
    return render_template('categories_index.html', categories=categories.values())


@portal.route('/category/<cat_id>/<subcat_id>/<int:page>')
@portal.route('/category/<cat_id>/<int:page>', defaults={'subcat_id': None})
@cache.cached(timeout=8400)
def category_view(cat_id, subcat_id, page):
    categories = get_app_categories()
    category = categories.get(cat_id)
    if not category:
        abort(404)

    parent_category = category
    if subcat_id:
        category = None
        for c in parent_category.get_children():
            if c.get_id() == subcat_id:
                category = c
                break
        if not category:
            abort(404)

    sw_per_page = 25

    with session_scope() as session:
        # TODO: Do this inefficient filtering in advance
        dcats = []
        for c in category.get_desktop_groups():
            parts = c.split('::')
            if len(parts) <= 1:
                dcats.append(c)
            else:
                dcats.append(parts[-1])

        sw_query = (
            session.query(SoftwareComponent)
            .join(SoftwareComponent.pkgs_binary)
            .filter(SoftwareComponent.categories.overlap(cast(dcats, ARRAY(String()))))
            .order_by(SoftwareComponent.cid, BinaryPackage.version.desc())
            .distinct(SoftwareComponent.cid)
        )
        software = sw_query.slice((page - 1) * sw_per_page, page * sw_per_page).all()

        sw_total = sw_query.count()
        page_count = math.ceil(sw_total / sw_per_page)

        return render_template(
            'category_view.html',
            parent_category=parent_category,
            category=category,
            subcat_id=subcat_id,
            software=software,
            sw_per_page=sw_per_page,
            sw_total=sw_total,
            current_page=page,
            page_count=page_count,
        )

src/webswview/lkswview/software/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

import gi
from flask import Blueprint, abort, current_app, render_template
from sqlalchemy.orm import joinedload

from laniakea.db import BinaryPackage, SoftwareComponent, session_scope

from ..extensions import cache

gi.require_version('AppStream', '1.0')
from gi.repository import AppStream

software = Blueprint('software', __name__, url_prefix='/sw')


class ASComponent:
    """Helper class to work with raw AppStream data as JSON"""

    def __init__(self, data):
        self._d = data

    def url_for(self, kind: AppStream.UrlKind):
        return self._d.get('Url', {}).get(AppStream.url_kind_to_string(kind))

    @property
    def screenshots(self):
        return self._d.get('Screenshots', [])


def screenshot_get_orig_image_url(scr_data):
    img = scr_data.get('source-image')
    if img:
        return current_app.config['APPSTREAM_MEDIA_URL'] + '/' + img['url']
    return '#'


@software.route('/<cid>')
@cache.cached(timeout=240)
def details(cid):
    with session_scope() as session:
        # NOTE: We display the newest component here. Maybe we want to actually
        # display the different component data by-version?
        sws = (
            session.query(SoftwareComponent)
            .options(joinedload(SoftwareComponent.pkgs_binary).joinedload(BinaryPackage.suites))
            .join(SoftwareComponent.pkgs_binary)
            .filter(SoftwareComponent.cid == cid)
            .order_by(BinaryPackage.version.desc())
            .all()
        )
        if not sws:
            abort(404)

        # FIXME: This loop is probably inefficient...
        packages_map = dict()
        for sw in sws:
            for bpkg in sw.pkgs_binary:
                for suite in bpkg.suites:
                    if suite.name not in packages_map:
                        packages_map[suite.name] = list()
                    packages_map[suite.name].append(bpkg)

        # grab the most recent component
        sw = sws[0]

        # FIXME: We parse the whole component as JSON here - if this becomes a performance issue,
        # we could parse less or cache this aggressively
        cpt = ASComponent(sw.data)
        return render_template(
            'software/sw_details.html',
            AppStream=AppStream,
            screenshot_get_orig_image_url=screenshot_get_orig_image_url,
            ComponentKind=AppStream.ComponentKind,
            sw=sw,
            cpt=cpt,
            component_id=cid,
            packages_map=packages_map,
        )

src/webswview/templates/default/categories_index.html
{% extends 'layouts/base.html' %}

{% set page_title = 'Software categories' %}

{% block body_header %}
<h1 class="title is-size-3 is-size-4-mobile">Software categories</h1>
{% endblock %}

{% block breadcrumbs %}
<!--
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.index') }}">Portal</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            Software
        </li>
    </ol>
</nav>
-->
{% endblock %}

{% block body %}
<div class="columns is-multiline grid">

    {% for c in categories %}
        <div class="column is-one-third">
            <div class="container category-item">
                <a href="{{ url_for('portal.category_view', cat_id=c.get_id(), page=1) }}">
                    <div class="columns is-mobile">
                        <div class="column is-one-third">
                            <img class="align-middle" src="{{ url_for('static', filename='img/categories/%s.svg'|format(c.get_icon())) }}" alt="{{c.get_icon()}}">
                        </div>
                        <div class="column is-two-thirds description">
                                <h1 class="title is-size-5 is-size-6-mobile">{{c.get_name()}}</h1>
                                {% if c.get_summary() %}
                                    <h2 class="subtitle is-size-6 is-size-7-mobile">{{c.get_summary()}}</h2>
                                {% else %}
                                    <h2 class="subtitle is-size-6 is-size-7-mobile">{{c.get_children()|length}} subcategories</h2>
                                {% endif %}

                        </div>
                    </div>
                </a>
            </div>
        </div>
    {% endfor %}

</div>

{% endblock %}

src/webswview/templates/default/category_view.html
{% extends 'layouts/base.html' %}

{% if parent_category != category %}
  {% set page_title = 'Category %s/%s'|format(parent_category.get_name(), category.get_name()) %}
{% else %}
  {% set page_title = 'Category %s'|format(category.get_name()) %}
{% endif %}

{% block breadcrumbs %}
<!--
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.categories_index') }}">Software</a>
        </li>
        {% if parent_category != category %}
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.category_view', cat_id=parent_category.get_id(), page=1) }}">{{parent_category.get_name()}}</a>
        </li>
        {% endif %}
        <li class="breadcrumb-item active" aria-current="page">
            {{category.get_name()}}
        </li>
    </ol>
</nav>
-->
{% endblock %}

{% block body %}
<div class="container">

        <h1>{{category.get_name()}}</h1>


        {% if category.has_children() %}
        <div class="columns is-multiline is-mobile grid">
            {% for sc in category.get_children() %}
            <div class="column is-narrow">

                <a class="button" href="{{ url_for('portal.category_view', cat_id=parent_category.get_id(), subcat_id=sc.get_id(), page=1) }}">{{sc.get_name()}}</a>
            </div>
            {% endfor %}
        </div>
        {% endif %}



        {% if current_page == 1 and not software %}
        <h2>
          No software was found in this section!
        </h2>
        {% endif %}

        <div class="columns is-multiline is-mobile grid">

            {% for sw in software %}
            <div class="column is-one-fifth-desktop is-half-mobile">
                <a class="list-group-item" href="{{ url_for('software.details', cid=sw.cid) }}">
                <div class="box app-item is-horizontal-center">

                    <p>
                        <figure class="image has-image-centered is-64x64">
                        {% if sw.icon_name %}
                            <img src="{{ config.APPSTREAM_MEDIA_URL + '/' + sw.gcid + '/icons/64x64/' + sw.icon_name }}" alt="Icon">
                        {% else %}
                            <img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==" alt="Icon">
                        {% endif %}
                        </figure>
                    <p>

                    <p class="has-text-centered is-size-6 is-size-7-mobile app-name">
                        {{sw.name}}
                    </p>
                    <p class="has-text-centered is-size-6 is-size-7-mobile badges">
                        {% if sw.is_free %}
                        <i class="fas fa-heart badge" title="Respects Freedom"></i>&nbsp;
                        {% endif %}
                        <!--
                        <i class="fas fa-shield-alt badge" title="Verifiable"></i>&nbsp;
                        <i class="fas fa-mobile badge" title="Mobile friendly"></i>&nbsp;
                        -->
                    </p>
                </div>
                </a>
            </div>
            {% endfor %}
        </div>

    {% if page_count > 1 %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
        <a class="pagination-previous" href="{{ url_for('portal.category_view', cat_id=parent_category.get_id(), subcat_id=subcat_id, page=current_page-1) if current_page > 1 else '#'}}">Previous</a>
        <a class="pagination-next" href="{{ url_for('portal.category_view', cat_id=parent_category.get_id(), subcat_id=subcat_id, page=current_page+1) if current_page < page_count else '#'}}">Next page</a>

        <ul class="pagination-list">

            <li>
                <a class="pagination-link {{'is-current' if 1 == current_page }}" href="{{ url_for('portal.category_view', cat_id=parent_category.get_id(), subcat_id=subcat_id, page=1) }}">1</a>
            </li>

            {% if page_count > 7 and current_page > 3 %}
            <li><span class="pagination-ellipsis">&hellip;</span></li>
            {% endif %}

            {% for i in range(2, page_count) %}
                {% if page_count < 8 or i < current_page + 2 and i > current_page - 2 or current_page < 4 and i < 6 or current_page > page_count - 3 and i > page_count - 5 %}

                <li>
                    <a class="pagination-link {{'is-current' if i == current_page }}" href="{{ url_for('portal.category_view', cat_id=parent_category.get_id(), subcat_id=subcat_id, page=i) }}">{{i}}</a>
                </li>

                {% endif %}
            {% endfor %}

            {% if page_count > 7 and current_page < page_count - 2 %}
            <li><span class="pagination-ellipsis">&hellip;</span></li>
            {% endif %}


            <li>
                <a class="pagination-link {{'is-current' if page_count == current_page }}" href="{{ url_for('portal.category_view', cat_id=parent_category.get_id(), subcat_id=subcat_id, page=page_count) }}">{{page_count}}</a>
            </li>

        </ul>
    </nav>
    {% endif %}

</div>


{% endblock %}

src/webswview/templates/default/index.html
{% extends 'layouts/base.html' %}

{% set page_title = 'Overview' %}

{% block body_header %}
<!-- Hero section -->
<div class="hero">
    <div class="columns is-desktop">
        <div class="column-inner" style="height: 300px">
            <h1>{{ config.PROJECT }} <span>Software</span></h1>

            <p>Welcome to {{ config.PROJECT }} software search!</p>
        </div>
    </div>
</div>

<!-- Browse section -->
<section class="section">
    <div class="container search">
        <div class="columns is-centered is-vcentered is-mobile">
            <div class="column is-narrow has-text-centered">
                <a class="button is-primary" href="{{ url_for('portal.categories_index') }}">Browse the catalog</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block body %}


{% endblock %}

src/webswview/templates/default/repo_index.html
{% extends 'layouts/base.html' %}

{% set page_title = 'Repositories & Suites' %}

{% block body_header %}

{% endblock %}

{% block breadcrumbs %}
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.repo_index') }}">Packages</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            Repositories
        </li>
    </ol>
</nav>
{% endblock %}

{% block body %}

<div class="columns">
    <div class="column">
        <h1 class="h2">Available Repositories</h1>
    </div>

    <div class="column is-one-quarter-desktop search">
        <form class="form-inline" action="/search_pkg" method="GET">
            <p class="control has-icons-left">
                <input id="term" name="term" class="input is-rounded" type="text" placeholder="Find a package...">
                <span class="icon is-left">
                    <i class="fas fa-search"></i>
                </span>

            </p>
        </form>
    </div>

</div>

<div class="tabs is-centered is-boxed">
  <ul>
    {% for repo in repos %}
      {% if repo.name == selected_repo.name %}
      <li class="is-active">
      {% else %}
      <li>
      {% endif %}
          <a href="{{ url_for('portal.repo_index', repo_name=repo.name) }}">
            <span class="icon is-small"><i class="fa-solid {{ 'fa-bug' if repo.is_debug else 'fa-cubes' }}" aria-hidden="true"></i></span>
            <span>{{repo.name}}</span>
          </a>
      </li>
    {% endfor %}
  </ul>
</div>

<h3 class="subtitle is-3">Suites</h3>
<div class="columns is-multiline grid" style="margin-top: 0;">
{% for rss in selected_repo.suite_settings %}
    {% set btn_style = 'is-success' %}
    {% if rss.suite.parent %}
      {% set btn_style = 'is-white' %}
    {% endif %}
    {% if rss.accept_uploads %}
      {% set btn_style = 'is-info' %}
    {% endif %}
    {% if rss.devel_target %}
      {% set btn_style = 'is-warning' %}
    {% endif %}
    <div class="column is-one-quarter">
        <a href="{{ url_for('portal.sections_index', repo_name=selected_repo.name, suite_name=rss.suite.name) }}">
            <div class="notification {{btn_style}} suite-btn">

                <p><strong>{{rss.suite.name}}</strong></p>
                <p>
                {% if rss.suite.parent %}
                    <small>Overlay for {{rss.suite.parent.name}}</small><br/>
                {% endif %}
                {% if rss.accept_uploads %}
                    <small>Accepts uploads</small><br/>
                {% endif %}
                {% if rss.devel_target %}
                    <small>Development target</small><br/>
                {% endif %}
                </p>

            </div>
        </a>
    </div>
{% endfor %}

</div>

{% endblock %}

src/webswview/templates/default/section_view.html
{% extends 'layouts/base.html' %}

{% set page_title = 'Section %s in %s:%s (%s)'|format(section.title, repo_suite.repo.name, repo_suite.suite.name, current_page) %}

{% block body_header %}

{% endblock %}

{% block breadcrumbs %}
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.repo_index') }}">Packages</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.repo_index', repo_name=repo_suite.repo.name) }}">{{repo_suite.repo.name}}</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.sections_index', repo_name=repo_suite.repo.name, suite_name=repo_suite.suite.name) }}">{{repo_suite.suite.name}}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {{section.title}}
        </li>
    </ol>
</nav>
{% endblock %}

{% block body %}

<div class="columns">
    <div class="column">
        <h2>Contents of section "{{section.title}}" in suite "{{repo_suite.suite.name}}"</h2>
    </div>
    <div class="column is-one-quarter-desktop search">
        <form class="form-inline" action="/search_pkg" method="GET">
            <p class="control has-icons-left">
                <input id="term" name="term" class="input is-rounded" type="text" placeholder="Find a package...">
                <span class="icon is-left">
                    <i class="fas fa-search"></i>
                </span>

            </p>
        </form>
    </div>
</div>

{% if current_page == 1 and not packages%}
<div class="alert alert-dark" role="alert">
  No packages were found in this section!
</div>
{% endif %}

<div class="package-items">
    {% for p in packages %}
    <div>
        <a class="border-box" href="{{ url_for('packages.bin_package_details',
                                               repo_name=repo_suite.repo.name,
                                               suite_name=repo_suite.suite.name,
                                               name=p.name) }}">

            <div class="columns is-mobile">
                <div class="column">
                    <strong>{{p.name}}</strong>
                    <p>{{p.summary}}</p>
                </div>
                <div class="column is-narrow">
                    {% if p.component.is_primary() %}
                        {% set component_badge_style = 'badge-primary' %}
                    {% elif p.component.is_nonfree() %}
                        {% set component_badge_style = 'badge-danger' %}
                    {% else %}
                        {% set component_badge_style = 'badge-secondary' %}
                    {% endif %}

                    <small><span class="badge {{component_badge_style}} badge-pill">{{p.component.name}}</span></small>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}

</div>

<br/>

{% if page_count > 1 %}
<nav class="pagination is-centered" role="navigation" aria-label="pagination">
    <a class="pagination-previous" href="{{ url_for('portal.section_view',
                                                     repo_name=repo_suite.repo.name,
                                                     suite_name=repo_suite.suite.name,
                                                     section_name=section.name,
                                                     page=current_page-1) if current_page > 1 else '#'}}">Previous</a>
    <a class="pagination-next" href="{{ url_for('portal.section_view',
                                                repo_name=repo_suite.repo.name,
                                                suite_name=repo_suite.suite.name,
                                                section_name=section.name,
                                                page=current_page+1) if current_page < page_count else '#'}}">Next page</a>

    <ul class="pagination-list">
        <li>
            <a class="pagination-link {{'is-current' if 1 == current_page }}" href="{{ url_for('portal.section_view',
                                                                                               repo_name=repo_suite.repo.name,
                                                                                               suite_name=repo_suite.suite.name,
                                                                                               section_name=section.name, page=1) }}">1</a>
        </li>

        {% if page_count > 7 and current_page > 3 %}
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}

        {% for i in range(2, page_count) %}
            {% if page_count < 8 or i < current_page + 2 and i > current_page - 2 or current_page < 4 and i < 6 or current_page > page_count - 3 and i > page_count - 5 %}

            <li>
                <a class="pagination-link {{'is-current' if i == current_page }}" href="{{ url_for('portal.section_view',
                                                                                                    repo_name=repo_suite.repo.name,
                                                                                                    suite_name=repo_suite.suite.name,
                                                                                                    section_name=section.name, page=i) }}">{{i}}</a>
            </li>

            {% endif %}
        {% endfor %}

        {% if page_count > 7 and current_page < page_count - 2 %}
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}


        <li>
            <a class="pagination-link {{'is-current' if page_count == current_page }}" href="{{ url_for('portal.section_view',
                                                                                                         repo_name=repo_suite.repo.name,
                                                                                                         suite_name=repo_suite.suite.name,
                                                                                                         section_name=section.name,
                                                                                                         page=page_count) }}">{{page_count}}</a>
        </li>
    </ul>
</nav>
{% endif %}

{% endblock %}

src/webswview/templates/default/sections_index.html
{% extends 'layouts/base.html' %}

{% set page_title = 'Sections in ' + repo_suite.suite.name %}

{% block body_header %}

{% endblock %}

{% block breadcrumbs %}
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.repo_index') }}">Packages</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ url_for('portal.repo_index', repo_name=repo_suite.repo.name) }}">{{repo_suite.repo.name}}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {{repo_suite.suite.name}}
        </li>
    </ol>
</nav>
{% endblock %}

{% block body %}

<div class="columns">
    <div class="column">
        <h1 class="h2">Sections in {{repo_suite.suite.name}}</h1>
    </div>
    <div class="column is-one-quarter-desktop search">
        <form class="form-inline" action="/search_pkg" method="GET">
            <p class="control has-icons-left">
                <input id="term" name="term" class="input is-rounded" type="text" placeholder="Find a package...">
                <span class="icon is-left">
                    <i class="fas fa-search"></i>
                </span>

            </p>
        </form>
    </div>

</div>
<div class="columns is-multiline grid">

    {% for section in sections %}
    <div class="column is-one-third">
        <a href="{{ url_for('portal.section_view',
                            repo_name=repo_suite.repo.name,
                            suite_name=repo_suite.suite.name,
                            section_name=section.name,
                            page=1) }}" class="card-link">
        <div class="container category-item">
            <strong>{{section.title}}</strong><br/>
            <span>{{section.summary}}</span>
        </div>
        </a>
    </div>
    {% endfor %}

</div>

{% endblock %}