src/webdash/lkweb/depcheck/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

import json
import math
from datetime import UTC, datetime, timedelta
from dataclasses import dataclass

from flask import Blueprint, abort, redirect, render_template

from laniakea.db import (
    PackageType,
    ArchiveSuite,
    DebcheckIssue,
    StatsEventKind,
    ArchiveRepoSuiteSettings,
    session_scope,
    make_stats_key,
)
from laniakea.archive import repo_suite_settings_for

from ..utils import is_uuid, fetch_statistics_for
from ..extensions import cache

depcheck = Blueprint('depcheck', __name__, url_prefix='/depcheck')


@dataclass
class RepoSuiteIssueOverview:
    rss: ArchiveRepoSuiteSettings
    src_issues_count: int = 0
    bin_issues_count: int = 0


@depcheck.route('/')
@cache.memoize(10 * 60)
def index():
    with session_scope() as session:
        repo_suites = (
            session.query(ArchiveRepoSuiteSettings)
            .join(ArchiveRepoSuiteSettings.suite)
            .filter(ArchiveRepoSuiteSettings.repo.has(is_debug=False))
            .order_by(ArchiveSuite.name.desc())
            .all()
        )

        rss_with_issues = []
        rss_good = []
        for rss in repo_suites:
            dci_src_count = (
                session.query(DebcheckIssue.uuid)
                .filter(
                    DebcheckIssue.package_type == PackageType.SOURCE,
                    DebcheckIssue.repo_id == rss.repo_id,
                    DebcheckIssue.suite_id == rss.suite_id,
                )
                .count()
            )
            dci_bin_count = (
                session.query(DebcheckIssue.uuid)
                .filter(
                    DebcheckIssue.package_type == PackageType.BINARY,
                    DebcheckIssue.repo_id == rss.repo_id,
                    DebcheckIssue.suite_id == rss.suite_id,
                )
                .count()
            )
            if dci_src_count != 0 or dci_bin_count != 0:
                rss_with_issues.append(RepoSuiteIssueOverview(rss, dci_src_count, dci_bin_count))
            else:
                rss_good.append(RepoSuiteIssueOverview(rss))

        return render_template(
            'depcheck/index.html', repo_suites_with_issues=rss_with_issues, repo_suites_good=rss_good
        )


@depcheck.route('/<repo_name>/<suite_name>/<ptype>/')
@depcheck.route('/<repo_name>/<suite_name>/<ptype>')
def issue_list_shortcut(repo_name, suite_name, ptype):
    """Convenience redirect to the full issue list page."""
    with session_scope() as session:
        suite = session.query(ArchiveSuite).filter(ArchiveSuite.name == suite_name).one_or_none()
        if not suite:
            abort(404)

        return redirect(
            '/depcheck/{}/{}/{}/{}/1'.format(repo_name, suite_name, ptype, suite.primary_architecture.name), code=302
        )


@cache.memoize(30 * 60)
def fetch_depcheck_statistics_for(session, ptype: PackageType, repo_name: str, suite_name: str, arch_name: str) -> str:
    start_at = datetime.now(UTC) - timedelta(days=120)

    stat_key = make_stats_key(
        StatsEventKind.DEPCHECK_ISSUES_SRC if ptype == PackageType.SOURCE else StatsEventKind.DEPCHECK_ISSUES_BIN,
        repo_name,
        suite_name,
        arch_name,
    )
    return json.dumps(fetch_statistics_for(session, stat_key, start_at))


@depcheck.route('/<repo_name>/<suite_name>/<ptype>/<arch_name>/<int:page>')
def issue_list(repo_name, suite_name, ptype, arch_name, page):
    if ptype == 'binary':
        package_type = PackageType.BINARY
    else:
        package_type = PackageType.SOURCE

    with session_scope() as session:
        rss = repo_suite_settings_for(session, repo_name, suite_name, fail_if_missing=False)
        if not rss:
            abort(404)

        issues_per_page = 50
        issues_total = (
            session.query(DebcheckIssue)
            .filter(DebcheckIssue.package_type == package_type)
            .filter(DebcheckIssue.repo_id == rss.repo.id)
            .filter(DebcheckIssue.suite_id == rss.suite.id)
            .filter(DebcheckIssue.architectures.any(arch_name))
            .count()
        )
        page_count = math.ceil(issues_total / issues_per_page)

        issues = (
            session.query(DebcheckIssue)
            .filter(DebcheckIssue.package_type == package_type)
            .filter(DebcheckIssue.repo_id == rss.repo.id)
            .filter(DebcheckIssue.suite_id == rss.suite.id)
            .filter(DebcheckIssue.architectures.any(arch_name))
            .order_by(DebcheckIssue.package_name)
            .slice((page - 1) * issues_per_page, page * issues_per_page)
            .all()
        )

        if page <= 1:
            stats_raw = fetch_depcheck_statistics_for(session, package_type, repo_name, suite_name, arch_name)
        else:
            stats_raw = ''

        return render_template(
            'depcheck/issues_list.html',
            ptype=ptype,
            issues=issues,
            rss=rss,
            arch_name=arch_name,
            issues_per_page=issues_per_page,
            issues_total=issues_total,
            current_page=page,
            page_count=page_count,
            stats_raw=stats_raw,
        )


@depcheck.route('/<repo_name>/<suite_name>/issue/<uuid>')
def issue_details(repo_name, suite_name, uuid):
    if not is_uuid(uuid):
        abort(404)

    with session_scope() as session:
        rss = repo_suite_settings_for(session, repo_name, suite_name, fail_if_missing=False)
        if not rss:
            abort(404)

        issue = (
            session.query(DebcheckIssue)
            .filter(DebcheckIssue.repo_id == rss.repo.id)
            .filter(DebcheckIssue.suite_id == rss.suite.id)
            .filter(DebcheckIssue.uuid == uuid)
            .one_or_none()
        )
        if not issue:
            abort(404)

        # cache information (as it has to be decoded from json)
        missing = issue.missing
        conflicts = issue.conflicts
        ptype = 'source' if issue.package_type == PackageType.SOURCE else 'binary'

        return render_template(
            'depcheck/issue.html',
            PackageType=PackageType,
            ptype=ptype,
            issue=issue,
            arch_name=', '.join(issue.architectures),
            rss=rss,
            missing=missing,
            conflicts=conflicts,
        )

src/webdash/lkweb/jobs/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

import json
import math
from enum import Enum, auto
from datetime import UTC, datetime, timedelta

from flask import Blueprint, abort, request, current_app, render_template

import laniakea.typing as T
from laniakea.db import (
    Job,
    JobKind,
    JobResult,
    JobStatus,
    PackageType,
    SparkWorker,
    DebcheckIssue,
    SourcePackage,
    StatsEventKind,
    ImageBuildRecipe,
    ArchiveArchitecture,
    session_scope,
    make_stats_key_jobqueue,
)
from laniakea.utils import get_dir_shorthand_for_uuid

from ..utils import is_uuid, humanized_timediff, fetch_statistics_for
from ..extensions import cache

jobs = Blueprint('jobs', __name__, url_prefix='/jobs')


class JobQueueState(Enum):
    PENDING = auto()
    PENDING_BLOCKED = auto()
    COMPLETED = auto()


def fetch_queue_statistics_for(
    session, kind: StatsEventKind, arch_name: str, start_at: datetime
) -> list[dict[str, T.Any]] | None:
    stat_key = make_stats_key_jobqueue(kind, arch_name)
    return fetch_statistics_for(session, stat_key, start_at)


@cache.cached(timeout=30 * 60, key_prefix='full_job_queue_statistics')
def get_full_queue_statistics(session) -> tuple[str, str]:
    pending_stats = {}
    depwait_stats = {}
    earliest_time = datetime.now(UTC) - timedelta(days=365)
    for arch in session.query(ArchiveArchitecture).filter(ArchiveArchitecture.name != 'all').all():
        pending_stats[arch.name] = fetch_queue_statistics_for(
            session, StatsEventKind.JOB_QUEUE_PENDING, arch.name, earliest_time
        )
        depwait_stats[arch.name] = fetch_queue_statistics_for(
            session, StatsEventKind.JOB_QUEUE_DEPWAIT, arch.name, earliest_time
        )
    return json.dumps(pending_stats), json.dumps(depwait_stats)


def title_for_job(session, job):
    '''
    Get a human readble title for the given job.
    '''

    title = 'Job for {}'.format(job.module)
    if job.kind == JobKind.PACKAGE_BUILD:
        spkg = (
            session.query(SourcePackage)
            .filter(SourcePackage.source_uuid == job.trigger)
            .filter(SourcePackage.version == job.version)
            .one_or_none()
        )
        if not spkg:
            return title
        return 'Build {} {} on {}'.format(spkg.name, job.version, job.architecture)
    elif job.kind == JobKind.OS_IMAGE_BUILD:
        recipe = session.query(ImageBuildRecipe).filter(ImageBuildRecipe.uuid == job.trigger).one_or_none()
        if not recipe:
            return title
        return 'OS Image {}'.format(recipe.name)

    return title


@jobs.route('/queue/<int:page>')
def queue(page):
    with session_scope() as session:
        queue_state = JobQueueState.PENDING_BLOCKED if request.args.get('blocked') == 'true' else JobQueueState.PENDING
        jobs_per_page = 50
        jobs_base_q = session.query(Job).filter(Job.status != JobStatus.DONE, Job.status != JobStatus.TERMINATED)
        if queue_state == JobQueueState.PENDING:
            jobs_base_q = jobs_base_q.filter(Job.status != JobStatus.DEPWAIT)

        jobs_total = jobs_base_q.count()
        page_count = math.ceil(jobs_total / jobs_per_page)

        jobs = jobs_base_q.order_by(Job.time_created).slice((page - 1) * jobs_per_page, page * jobs_per_page).all()

        return render_template(
            'jobs/queue.html',
            JobStatus=JobStatus,
            JobResult=JobResult,
            JobQueueState=JobQueueState,
            humanized_timediff=humanized_timediff,
            session=session,
            queue_state=queue_state,
            title_for_job=title_for_job,
            jobs=jobs,
            jobs_per_page=jobs_per_page,
            jobs_total=jobs_total,
            current_page=page,
            page_count=page_count,
        )


@jobs.route('/queue/completed/<int:page>')
def list_completed(page):
    with session_scope() as session:
        jobs_per_page = 50
        max_pages_count = 3
        jobs_base_q = (
            session.query(Job)
            .filter(Job.status.in_((JobStatus.DONE, JobStatus.TERMINATED)), ~Job.time_finished.is_(None))
            .order_by(Job.time_finished.desc())
            .limit(jobs_per_page * max_pages_count)
        )
        jobs_total = jobs_base_q.count()
        page_count = math.ceil(jobs_total / jobs_per_page)

        jobs = jobs_base_q.slice((page - 1) * jobs_per_page, page * jobs_per_page).all()

        return render_template(
            'jobs/queue.html',
            JobStatus=JobStatus,
            JobResult=JobResult,
            JobQueueState=JobQueueState,
            humanized_timediff=humanized_timediff,
            session=session,
            queue_state=JobQueueState.COMPLETED,
            title_for_job=title_for_job,
            jobs=jobs,
            jobs_per_page=jobs_per_page,
            jobs_total=jobs_total,
            current_page=page,
            page_count=page_count,
        )


@jobs.route('/queue/stats')
@cache.cached(timeout=10 * 60)
def queue_stats():
    with session_scope() as session:
        pending_stats, depwait_stats = get_full_queue_statistics(session)

        return render_template(
            'jobs/queue_stats.html',
            pending_stats=pending_stats,
            depwait_stats=depwait_stats,
        )


def prefix_list_entries(lst, prefix: str) -> list[str]:
    return [prefix + e for e in lst]


@jobs.route('/workers')
def workers():
    with session_scope() as session:
        workers = session.query(SparkWorker).all()

        return render_template(
            'jobs/workers.html',
            workers=workers,
            humanized_timediff=humanized_timediff,
            prefix_list_entries=prefix_list_entries,
        )


@jobs.route('/job/<uuid>')
def job(uuid):
    if not is_uuid(uuid):
        abort(404)

    with session_scope() as session:
        job = session.query(Job).filter(Job.uuid == uuid).one_or_none()
        if not job:
            abort(404)

        worker = session.query(SparkWorker).filter(SparkWorker.uuid == job.worker).one_or_none()

        log_url = None
        firehose_url = None
        if job.result in (JobResult.SUCCESS, JobResult.FAILURE, JobResult.FAILURE_DEPENDENCY):
            log_root = current_app.config['LOG_STORAGE_URL'] + '/' + get_dir_shorthand_for_uuid(job.uuid) + '/'
            log_url = log_root + str(job.uuid) + '.log'
            firehose_url = log_root + 'firehose/' + str(job.uuid) + '.firehose.xml'

        job_title = 'Job for {}'.format(job.module)
        if job.kind == JobKind.PACKAGE_BUILD:
            spkg = (
                session.query(SourcePackage)
                .filter(SourcePackage.source_uuid == job.trigger)
                .filter(SourcePackage.version == job.version)
                .one_or_none()
            )
            if spkg:
                job_title = 'Build {} {} on {}'.format(spkg.name, job.version, job.architecture)

            suite_name = 'unknown'
            if job.suite:
                suite_name = job.suite.name

            dep_issues = []
            if spkg and job.suite:
                suite_name = job.suite.name
                dep_issues = (
                    session.query(DebcheckIssue)
                    .filter(DebcheckIssue.package_type == PackageType.SOURCE)
                    .filter(DebcheckIssue.suite_id == job.suite.id)
                    .filter(DebcheckIssue.package_name == spkg.name)
                    .filter(DebcheckIssue.package_version == spkg.version)
                    .filter(DebcheckIssue.architectures.overlap([job.architecture, 'any']))
                    .all()
                )

            return render_template(
                'jobs/job_pkgbuild.html',
                PackageType=PackageType,
                humanized_timediff=humanized_timediff,
                JobStatus=JobStatus,
                JobResult=JobResult,
                job=job,
                job_title=job_title,
                worker=worker,
                spkg=spkg,
                suite_name=suite_name,
                dep_issues=dep_issues,
                log_url=log_url,
                firehose_url=firehose_url,
            )
        elif job.kind == JobKind.OS_IMAGE_BUILD:
            recipe = session.query(ImageBuildRecipe).filter(ImageBuildRecipe.uuid == job.trigger).one_or_none()
            if recipe:
                job_title = 'OS Image {}'.format(recipe.name)

            return render_template(
                'jobs/job_osimage.html',
                humanized_timediff=humanized_timediff,
                JobStatus=JobStatus,
                JobResult=JobResult,
                job=job,
                job_title=job_title,
                worker=worker,
                recipe=recipe,
                log_url=log_url,
            )
        else:
            return render_template(
                'jobs/job_generic.html',
                humanized_timediff=humanized_timediff,
                JobStatus=JobStatus,
                JobResult=JobResult,
                job=job,
                job_title=job_title,
                worker=worker,
                log_url=log_url,
            )


@jobs.route('/job/log/<uuid>')
def view_log(uuid):
    if not is_uuid(uuid):
        abort(404)

    with session_scope() as session:
        job = session.query(Job).filter(Job.uuid == uuid).one_or_none()
        if not job:
            abort(404)

        log_url = None
        firehose_url = None
        if job.result in (JobResult.SUCCESS, JobResult.FAILURE, JobResult.FAILURE_DEPENDENCY):
            log_root = current_app.config['LOG_STORAGE_URL'] + '/' + get_dir_shorthand_for_uuid(job.uuid) + '/'
            log_url = log_root + str(job.uuid) + '.log'
            firehose_url = log_root + 'firehose/' + str(job.uuid) + '.firehose.xml'

        if not log_url:
            abort(404)

        log_title = str(uuid)[:11]

src/webdash/lkweb/osimages/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

from flask import Blueprint, render_template

from laniakea.db import Job, JobResult, ImageFormat, ImageBuildRecipe, session_scope

from ..utils import humanized_timediff

osimages = Blueprint('osimages', __name__, url_prefix='/osimages')


def last_jobs_for_recipe(session, recipe):
    return session.query(Job).filter(Job.trigger == recipe.uuid).order_by(Job.time_created.desc()).slice(0, 4).all()


@osimages.route('/')
def index():
    with session_scope() as session:
        recipes = (
            session.query(ImageBuildRecipe).order_by(ImageBuildRecipe.suite.desc(), ImageBuildRecipe.name.desc()).all()
        )

        return render_template(
            'osimages/index.html',
            session=session,
            last_jobs_for_recipe=last_jobs_for_recipe,
            humanized_timediff=humanized_timediff,
            ImageFormat=ImageFormat,
            JobResult=JobResult,
            recipes=recipes,
        )

src/webdash/templates/default/layouts/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{{ page_title }}{% endblock %} - {{ config.PROJECT }}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome/fontawesome.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome/all.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/laniakea.css') }}"/>
    {% block css %}{% endblock %}
</head>
{% block js_pre %}{% endblock %}

<body>
    <nav class="navbar is-white">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item brand-text" href="{{ url_for('overview.index') }}">
                {{ config.PROJECT }}
                </a>
                <div class="navbar-burger burger" data-target="navMenu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div id="navMenu" class="navbar-menu">
                <div class="navbar-start">
                 <!-- top navbar not used at the moment -->
                </div>

            </div>
        </div>
    </nav>

    {% block container %}
    <div class="container">
        <div class="columns">
            <div class="column is-2">
                <aside class="menu">
                {% set active_menu = active_menu|default('overview') -%}

                <p class="menu-label">
                    General
                </p>
                <ul class="menu-list">
                    <li><a class="{{'is-active' if active_menu == 'overview' }}" href="{{ url_for('overview.index') }}">
                       <i class="fas fa-solar-panel"></i>
                       Overview
                    </a></li>
                </ul>

                <p class="menu-label">
                   Package Archive
                </p>
                <ul class="menu-list">
                    <li><a><i class="fas fa-snowplow"></i> Transitions</a></li>

                    <li><a class="{{'is-active' if active_menu == 'migrations' }}" href="{{ url_for('migrations.index') }}">
                        <i class="fas fa-route"></i>
                        Migrations
                    </a></li>

                    <li><a class="{{'is-active' if active_menu == 'synchronization' }}" href="{{ url_for('synchronization.index') }}">
                        <i class="fa-solid fa-down-left-and-up-right-to-center"></i>
                        Synchronization
                    </a></li>

                    <li><a class="{{'is-active' if active_menu == 'depcheck' }}" href="{{ url_for('depcheck.index') }}">
                        <i class="fas fa-puzzle-piece"></i>
                        Dependency Check
                    </a></li>

                    <li><a><i class="fas fa-seedling"></i> Package Seeds</a></li>

                    <li><a class="{{'is-active' if active_menu == 'reviewqueues' }}" href="{{ url_for('review_queues.index') }}">
                        <i class="fa-solid fa-clipboard-list"></i>
                        Review Queues
                    </a></li>
                </ul>

		<p class="menu-label">
                   Building &amp; Delivery
                </p>
                <ul class="menu-list">
                    <li><a class="{{'is-active' if active_menu == 'osimages' }}" href="{{ url_for('osimages.index') }}">
                        <i class="fas fa-sd-card"></i>
                        Disk Images
                    </a></li>

                    <li><a class="{{'is-active' if active_menu == 'jobqueue' }}" href="{{ url_for('jobs.queue', page=1) }}">
                        <i class="fas fa-tasks"></i>
                        Job Queue
                    </a></li>

                    <li><a class="{{'is-active' if active_menu == 'workers' }}" href="{{ url_for('jobs.workers') }}">
                        <i class="fas fa-server"></i>
                        Workers
                    </a></li>
                </ul>

                </aside>
            </div>
            <div class="column is-12">
                <nav class="breadcrumb" aria-label="breadcrumbs">
                    {% block breadcrumbs %}{% endblock %}
                </nav>

                {% block flash_message %}
                   {% with messages = get_flashed_messages(with_categories=True) %}
                       {% if messages %}
                           {% for category, msg in messages %}
                               <div class="alert alert-{{ category }}">
                                   {{ msg|safe }}
                               </div>
                           {% endfor %}
                        {% endif %}
                    {% endwith %}
                {% endblock %}

                {% block body_header %}{% endblock %}

                {% block body %}{% endblock %}
            </div>
            {% endblock %}
        </div>
    </div>

    <footer class="footer">
        <div class="section-legal has-text-centered">
            <p>
                <small>
                    <a href="#">Back to top</a>
                </small>
	    </p>
            <p>
                <small>
                    Powered by
                    <a href="https://github.com/lkhq/laniakea">Laniakea</a>.
                </small>
            </p>
        </div>
    </footer>

    <script src="{{ url_for('static', filename='js/jquery/jquery.slim.min.js') }}"></script>
    {% block js %}{% endblock %}
</body>

</html>