src/webdash/lkweb/overview/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

from datetime import datetime

import pytz
import humanize
import sqlalchemy
from flask import Blueprint, render_template
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore

from laniakea import LocalConfig
from laniakea.db import (
    Job,
    JobStatus,
    BinaryPackage,
    DebcheckIssue,
    ArchiveRepository,
    ArchiveQueueNewEntry,
    session_scope,
)

from ..extensions import cache

overview = Blueprint('overview', __name__)
g_jobstore = None  # the jobstore can only be loaded once, so we globally cache it


def get_scheduler_jobstore():
    from laniakea.db import Base, Database

    global g_jobstore
    if g_jobstore is None:
        db = Database()
        g_jobstore = SQLAlchemyJobStore(engine=db.engine, tablename='maintenance_jobs', metadata=Base.metadata)
    return g_jobstore


def humanized_job_timediff(job):
    """
    Get time when the job will run next in a human-readable format
    as a string.
    """
    if not job:
        return 'Never'

    timediff = datetime.now(pytz.utc).replace(microsecond=0) - job.next_run_time.astimezone(pytz.utc)
    return humanize.naturaltime(timediff)


@overview.route('/')
@cache.cached(timeout=10)
def index():
    lconf = LocalConfig()
    with session_scope() as session:
        master_repo_id = (
            session.query(ArchiveRepository.id).filter(ArchiveRepository.name == lconf.master_repo_name).one()[0]
        )

        # fetch basic statistics!
        repo_count = session.query(ArchiveRepository.id).count()
        package_count = (
            session.query(BinaryPackage.uuid)
            .filter(BinaryPackage.repo_id == master_repo_id)
            .distinct(BinaryPackage.name)
            .count()
        )
        jobs_pending_count = (
            session.query(Job.uuid)
            .filter(Job.status.in_([JobStatus.WAITING, JobStatus.SCHEDULED, JobStatus.RUNNING]))
            .count()
        )
        debcheck_issues_count = (
            session.query(DebcheckIssue.uuid)
            .filter(DebcheckIssue.repo_id == master_repo_id)
            .distinct(DebcheckIssue.package_name)
            .count()
        )
        review_queue_count = (
            session.query(ArchiveQueueNewEntry.id)
            .filter(
                ArchiveQueueNewEntry.package.has(repo_id=master_repo_id),
            )
            .count()
        )

        # fetch info about scheduled maintenance tasks
        jobstore = get_scheduler_jobstore()
        scheduler_configured = True
        rubicon_nextrun_time = 'disabled'
        publish_nextrun_time = 'disabled'
        spears_nextrun_time = 'disabled'
        debcheck_nextrun_time = 'disabled'
        synchrotron_nextrun_time = 'disabled'
        expire_nextrun_time = 'disabled'
        try:
            job = jobstore.lookup_job('rubicon')
        except sqlalchemy.exc.ProgrammingError:
            # the jobs table likely hasn't been created yet, so we will make no further attempts to fetch its data
            scheduler_configured = False
        if scheduler_configured:
            rubicon_nextrun_time = humanized_job_timediff(job)
            job = jobstore.lookup_job('publish-repos')
            publish_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('expire-repos')
            expire_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('spears-migrate')
            spears_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('debcheck')
            debcheck_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('synchrotron-autosync')
            synchrotron_nextrun_time = humanized_job_timediff(job)

        return render_template(
            'index.html',
            repo_count=repo_count,
            package_count=package_count,
            review_queue_count=review_queue_count,
            jobs_pending_count=jobs_pending_count,
            debcheck_issues_count=debcheck_issues_count,
            rubicon_nextrun_time=rubicon_nextrun_time,
            publish_nextrun_time=publish_nextrun_time,
            expire_nextrun_time=expire_nextrun_time,
            spears_nextrun_time=spears_nextrun_time,
            debcheck_nextrun_time=debcheck_nextrun_time,
            synchrotron_nextrun_time=synchrotron_nextrun_time,
        )

src/webdash/lkweb/synchronization/__init__.py
# -*- coding: utf-8 -*-

from .views import synchronization

__all__ = ['synchronization']

src/webdash/lkweb/synchronization/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

from flask import Blueprint, abort, render_template

from laniakea.db import (
    ArchiveSuite,
    SynchrotronIssue,
    SynchrotronConfig,
    SyncBlacklistEntry,
    SynchrotronIssueKind,
    session_scope,
)

from ..extensions import cache

synchronization = Blueprint('synchronization', __name__, url_prefix='/sync')


@synchronization.route('/')
@cache.cached(timeout=60 * 10)
def index():
    with session_scope() as session:
        sync_configs = (
            session.query(SynchrotronConfig).join(SynchrotronConfig.destination_suite).order_by(ArchiveSuite.name).all()
        )

        auto_syncs = []
        manual_syncs = []
        for sc in sync_configs:
            if sc.sync_auto_enabled:
                auto_syncs.append(sc)
            else:
                manual_syncs.append(sc)

        return render_template('synchronization/index.html', auto_syncs=auto_syncs, manual_syncs=manual_syncs)


@synchronization.route('<int:config_id>/issues')
def issues_table(config_id: int):
    with session_scope() as session:
        sync_config = session.query(SynchrotronConfig).filter(SynchrotronConfig.id == config_id).one_or_none()
        if not sync_config:
            abort(404)
        issues = session.query(SynchrotronIssue).filter(SynchrotronIssue.config_id == sync_config.id).all()

        return render_template(
            'synchronization/sync_issue_table.html',
            issues=issues,
            SyncIssueKind=SynchrotronIssueKind,
            sconf=sync_config,
        )


@synchronization.route('<int:config_id>/blacklist/')
def blacklist(config_id: int):
    with session_scope() as session:
        sync_config = session.query(SynchrotronConfig).filter(SynchrotronConfig.id == config_id).one_or_none()
        if not sync_config:
            abort(404)
        entries = session.query(SyncBlacklistEntry).filter(SyncBlacklistEntry.config_id == sync_config.id).all()

        return render_template('synchronization/blacklist.html', entries=entries, sconf=sync_config)

src/webdash/templates/default/synchronization/blacklist.html
{% extends 'layouts/base.html' %}

{% set active_menu = 'synchronization' %}
{% set page_title = 'Synchronization Blacklist' %}

{% block breadcrumbs %}
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li>
            <a href="{{ url_for('overview.index') }}">Home</a>
        </li>
        <li>
            <a href="{{ url_for('synchronization.index') }}">Sync</a>
        </li>
        <li>
          <p class="px-2">{{sconf.repo.name}}</p>
        </li>
        <li>
          <p class="px-2">{{sconf.destination_suite.name}} (from {{sconf.source.os_name}} {{sconf.source.suite_name}})</p>
        </li>
        <li class="is-active">
          <a href="#" aria-current="page">Denylist</a>
        </li>
    </ol>
</nav>
{% endblock %}

{% block body_header %}
<h1 class="title mb-4">Packages Prevented From Synchronization</h1>
{% endblock %}

{% block body %}
{% if not entries %}
<article class="message is-success">
    <div class="message-header">
        <p><span class="fa fa-check" aria-hidden="true"></span> Any package is permitted to enter the destination suite.</p>
    </div>
</article>
{% else %}

<table class="table is-striped is-hoverable">
    <thead>
      <tr>
        <th>Package</th>
        <th>Reason</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
    {% for entry in entries %}
        <tr>
          <th scope="row">{{entry.pkgname}}</th>
          <td>{{entry.reason}}</td>
          <td>{{ entry.time_created.strftime('%Y-%m-%d %H:%M %z') if entry.time_created else 'Unknown' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endif %}
{% endblock %}

src/webdash/templates/default/synchronization/index.html
{% extends 'layouts/base.html' %}

{% set active_menu = 'synchronization' %}
{% set page_title = 'Synchronization Issue Overview' %}

{% block breadcrumbs %}
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li>
            <a href="{{ url_for('overview.index') }}">Home</a>
        </li>
        <li class="is-active">
            <a href="#" aria-current="page">Sync</a>
        </li>
    </ol>
</nav>
{% endblock %}

{% block body_header %}
<h1 class="title mb-4">Package Synchronization Target Suites</h1>
{% endblock %}

{% block body %}
<div class="column is-10">

  <h4 class="subtitle is-4">Automatic Synchronization Tasks</h4>
  <div class="columns is-multiline is-mobile">
    {% for sconf in auto_syncs %}
      <div class="column is-half">

      <div class="card">
      <header class="card-header">
        <p class="card-header-title">
          <i class="fas fa-compress-arrows-alt"></i>&nbsp;{{sconf.destination_suite.name}}&nbsp;&nbsp;<span class="has-text-weight-light">from&nbsp;<i class="fas fa-expand-arrows-alt"></i>&nbsp;{{sconf.source.os_name}} {{sconf.source.suite_name}}</span>
        </p>
        <div class="p-3">
         <span class="tag is-rounded is-light"><i class="fa-solid fa-box-archive"></i>&nbsp;{{sconf.repo.name}}</span>
        </div>
      </header>

      <div class="card-content py-2">
          <div class="content">
              <p class="mb-1"></p>
              {% if sconf.sync_enabled %}<font class="fas fa-check" aria-hidden="true" color="green"></font>{% else %}<font class="fas fa-times" aria-hidden="true" color="orange"></font>{% endif %} Synchronization allowed<br/>
              {% if sconf.sync_binaries %}<font class="fas fa-check" aria-hidden="true" color="green"></font>{% else %}<font class="fas fa-times" aria-hidden="true" color="orange"></font>{% endif %} Pull binaries from origin<br/>
              {% if sconf.auto_cruft_remove %}<font class="fas fa-check" aria-hidden="true" color="green"></font>{% else %}<font class="fas fa-times" aria-hidden="true" color="orange"></font>{% endif %} Attempt auto cruft removal
          </div>
      </div>
      <footer class="card-footer">
          <a href="{{ url_for('synchronization.issues_table', config_id=sconf.id) }}" class="card-footer-item">Suite Sync Issue Table</a>
      </footer>
      </div>

      </div>
    {% endfor %}
  </div>

  <h4 class="subtitle is-4">Other Registered Synchronization Tasks</h4>
  <div class="columns is-multiline is-mobile">
    {% for sconf in manual_syncs %}
      <div class="column is-half">

      <div class="card">
      <header class="card-header">
        <p class="card-header-title">
          <i class="fas fa-compress-arrows-alt"></i>&nbsp;{{sconf.destination_suite.name}}&nbsp;&nbsp;<span class="has-text-weight-light">from&nbsp;<i class="fas fa-expand-arrows-alt"></i>&nbsp;{{sconf.source.os_name}} {{sconf.source.suite_name}}</span>
        </p>
        <div class="p-3">
         <span class="tag is-rounded is-light"><i class="fa-solid fa-box-archive"></i>&nbsp;{{sconf.repo.name}}</span>
        </div>
      </header>

      <div class="card-content py-2">
          <div class="content">
              <p class="mb-1"></p>
              {% if sconf.sync_enabled %}<font class="fas fa-check" aria-hidden="true" color="green"></font>{% else %}<font class="fas fa-times" aria-hidden="true" color="orange"></font>{% endif %} Synchronization allowed<br/>
              {% if sconf.sync_binaries %}<font class="fas fa-check" aria-hidden="true" color="green"></font>{% else %}<font class="fas fa-times" aria-hidden="true" color="orange"></font>{% endif %} Pull binaries from origin<br/>
              {% if sconf.auto_cruft_remove %}<font class="fas fa-check" aria-hidden="true" color="green"></font>{% else %}<font class="fas fa-times" aria-hidden="true" color="orange"></font>{% endif %} Attempt auto cruft removal
          </div>
      </div>
      </div>

      </div>
    {% endfor %}
  </div>

</div>
{% endblock %}

src/webdash/templates/default/synchronization/sync_issue_table.html
{% extends 'layouts/base.html' %}

{% set active_menu = 'synchronization' %}
{% set page_title = 'Synchronization Issue Overview / ' + sconf.destination_suite.name + ' (from ' + sconf.source.os_name + ' ' + sconf.source.suite_name %}

{% block breadcrumbs %}
<nav class="pt-3" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li>
          <a href="{{ url_for('overview.index') }}">Home</a>
        </li>
        <li>
          <a href="{{ url_for('synchronization.index') }}">Sync</a>
        </li>
        <li>
          <p class="px-2">{{sconf.repo.name}}</p>
        </li>
        <li>
          <p class="px-2">{{sconf.destination_suite.name}} (from {{sconf.source.os_name}} {{sconf.source.suite_name}})</p>
        </li>
        <li class="is-active">
          <a href="#" aria-current="page">Issues</a>
        </li>
    </ol>
</nav>
{% endblock %}

{% block body_header %}
<h1 class="title">Package Synchronization Issue Overview</h1>
<h2 class="subtitle is-4">for target <i>{{sconf.destination_suite.name}}</i> from source <i>{{sconf.source.os_name}} {{sconf.source.suite_name}}</i></h2>
{% endblock %}

{% block body %}
<div class="columns is-multiline is-mobile">
<div class="column is-12">

<div class="field is-horizontal">
  <div class="field-label is-normal has-text-left" style="flex-grow: 0;">
    <label class="label" id="filter-desc">Filter</label>
  </div>
  <div class="field-body">
    <div class="field is-expanded">
      <div class="control">
        <input id="filter" class="input" type="text" placeholder="e.g. a package name" aria-label="Filter" aria-describedby="filter-desc" />
      </div>
    </div>

    <div class="dropdown is-hoverable">
        <div class="dropdown-trigger">
            <button class="button" aria-haspopup="true" aria-controls="settings-menu">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span class="icon is-small">
                <i class="fas fa-angle-down" aria-hidden="true"></i>
            </span>
            </button>
        </div>
        <div class="dropdown-menu" id="settings-menu" role="menu">
            <div class="dropdown-content">
                <a class="dropdown-item" href="{{ url_for('synchronization.blacklist', config_id=sconf.id) }}">Ignored packages</a>
            </div>
        </div>
    </div>

  </div>
</div>

{% if not issues %}
<article class="message is-success">
    <div class="message-header">
        <p><span class="fa fa-check" aria-hidden="true"></span> No issues found!</p>
    </div>
</article>
{% else %}

<table class="table is-striped is-hoverable is-narrow">
    <thead>
      <tr>
        <th>Affected Package</th>
        <th>Direction</th>
        <th>Version in Target</th>
        <th>Version in Source</th>
        <th>Issue</th>
      </tr>
    </thead>
    <tbody class="searchable">
    {% for issue in issues %}
    <tr>
      <td>{{issue.package_name}}</td>
      <td>{{issue.source_suite}} <i class="fas fa-arrow-right"></i> {{issue.target_suite}}</td>
      <td>{{issue.target_version}}</td>
      <td>{{issue.source_version}}</td>
      <td>
        {%if issue.kind == SyncIssueKind.MERGE_REQUIRED %}
          <i class="fas fa-code-branch"></i> Requires manual merge of downstream changes with source.
        {% elif issue.kind == SyncIssueKind.MAYBE_CRUFT  %}
          <i class="fas fa-trash-alt"></i> This package is likely cruft and could be removed after manual review. {%if issue.details %}{{issue.details}}{% endif %}
        {% elif issue.kind == SyncIssueKind.SYNC_FAILED  %}
          <i class="fas fa-exclamation-triangle"></i> This package failed to synchronize. {%if issue.details %}{{issue.details}}{% endif %}
        {% elif issue.kind == SyncIssueKind.REMOVAL_FAILED  %}
          <i class="fas fa-bomb"></i> Unable to remove this package. {{issue.details}}
        {% else %}
          Error: {{issue.details}}
        {% endif %}
     </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endif %}

</div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function () {
    $('#filter').keyup(function () {
        var rex = new RegExp($(this).val(), 'i');
        $('.searchable tr').hide();
        $('.searchable tr').filter(function () {
            return rex.test($(this).text());
        }).show();
    });
});
</script>
{% endblock %}