src/webdash/lkweb/depcheck/__init__.py
# -*- coding: utf-8 -*-

from .views import depcheck

__all__ = ['depcheck']

src/webdash/lkweb/depcheck/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

import json
import math
from datetime import UTC, datetime, timedelta
from dataclasses import dataclass

from flask import Blueprint, abort, redirect, render_template

from laniakea.db import (
    PackageType,
    ArchiveSuite,
    DebcheckIssue,
    StatsEventKind,
    ArchiveRepoSuiteSettings,
    session_scope,
    make_stats_key,
)
from laniakea.archive import repo_suite_settings_for

from ..utils import is_uuid, fetch_statistics_for
from ..extensions import cache

depcheck = Blueprint('depcheck', __name__, url_prefix='/depcheck')


@dataclass
class RepoSuiteIssueOverview:
    rss: ArchiveRepoSuiteSettings
    src_issues_count: int = 0
    bin_issues_count: int = 0


@depcheck.route('/')
@cache.memoize(10 * 60)
def index():
    with session_scope() as session:
        repo_suites = (
            session.query(ArchiveRepoSuiteSettings)
            .join(ArchiveRepoSuiteSettings.suite)
            .filter(ArchiveRepoSuiteSettings.repo.has(is_debug=False))
            .order_by(ArchiveSuite.name.desc())
            .all()
        )

        rss_with_issues = []
        rss_good = []
        for rss in repo_suites:
            dci_src_count = (
                session.query(DebcheckIssue.uuid)
                .filter(
                    DebcheckIssue.package_type == PackageType.SOURCE,
                    DebcheckIssue.repo_id == rss.repo_id,
                    DebcheckIssue.suite_id == rss.suite_id,
                )
                .count()
            )
            dci_bin_count = (
                session.query(DebcheckIssue.uuid)
                .filter(
                    DebcheckIssue.package_type == PackageType.BINARY,
                    DebcheckIssue.repo_id == rss.repo_id,
                    DebcheckIssue.suite_id == rss.suite_id,
                )
                .count()
            )
            if dci_src_count != 0 or dci_bin_count != 0:
                rss_with_issues.append(RepoSuiteIssueOverview(rss, dci_src_count, dci_bin_count))
            else:
                rss_good.append(RepoSuiteIssueOverview(rss))

        return render_template(
            'depcheck/index.html', repo_suites_with_issues=rss_with_issues, repo_suites_good=rss_good
        )


@depcheck.route('/<repo_name>/<suite_name>/<ptype>/')
@depcheck.route('/<repo_name>/<suite_name>/<ptype>')
def issue_list_shortcut(repo_name, suite_name, ptype):
    """Convenience redirect to the full issue list page."""
    with session_scope() as session:
        suite = session.query(ArchiveSuite).filter(ArchiveSuite.name == suite_name).one_or_none()
        if not suite:
            abort(404)

        return redirect(
            '/depcheck/{}/{}/{}/{}/1'.format(repo_name, suite_name, ptype, suite.primary_architecture.name), code=302
        )


@cache.memoize(30 * 60)
def fetch_depcheck_statistics_for(session, ptype: PackageType, repo_name: str, suite_name: str, arch_name: str) -> str:
    start_at = datetime.now(UTC) - timedelta(days=120)

    stat_key = make_stats_key(
        StatsEventKind.DEPCHECK_ISSUES_SRC if ptype == PackageType.SOURCE else StatsEventKind.DEPCHECK_ISSUES_BIN,
        repo_name,
        suite_name,
        arch_name,
    )
    return json.dumps(fetch_statistics_for(session, stat_key, start_at))


@depcheck.route('/<repo_name>/<suite_name>/<ptype>/<arch_name>/<int:page>')
def issue_list(repo_name, suite_name, ptype, arch_name, page):
    if ptype == 'binary':
        package_type = PackageType.BINARY
    else:
        package_type = PackageType.SOURCE

    with session_scope() as session:
        rss = repo_suite_settings_for(session, repo_name, suite_name, fail_if_missing=False)
        if not rss:
            abort(404)

        issues_per_page = 50
        issues_total = (
            session.query(DebcheckIssue)
            .filter(DebcheckIssue.package_type == package_type)
            .filter(DebcheckIssue.repo_id == rss.repo.id)
            .filter(DebcheckIssue.suite_id == rss.suite.id)
            .filter(DebcheckIssue.architectures.any(arch_name))
            .count()
        )
        page_count = math.ceil(issues_total / issues_per_page)

        issues = (
            session.query(DebcheckIssue)
            .filter(DebcheckIssue.package_type == package_type)
            .filter(DebcheckIssue.repo_id == rss.repo.id)
            .filter(DebcheckIssue.suite_id == rss.suite.id)
            .filter(DebcheckIssue.architectures.any(arch_name))
            .order_by(DebcheckIssue.package_name)
            .slice((page - 1) * issues_per_page, page * issues_per_page)
            .all()
        )

        if page <= 1:
            stats_raw = fetch_depcheck_statistics_for(session, package_type, repo_name, suite_name, arch_name)
        else:
            stats_raw = ''

        return render_template(
            'depcheck/issues_list.html',
            ptype=ptype,
            issues=issues,
            rss=rss,
            arch_name=arch_name,
            issues_per_page=issues_per_page,
            issues_total=issues_total,
            current_page=page,
            page_count=page_count,
            stats_raw=stats_raw,
        )


@depcheck.route('/<repo_name>/<suite_name>/issue/<uuid>')
def issue_details(repo_name, suite_name, uuid):
    if not is_uuid(uuid):
        abort(404)

    with session_scope() as session:
        rss = repo_suite_settings_for(session, repo_name, suite_name, fail_if_missing=False)
        if not rss:
            abort(404)

        issue = (
            session.query(DebcheckIssue)
            .filter(DebcheckIssue.repo_id == rss.repo.id)
            .filter(DebcheckIssue.suite_id == rss.suite.id)
            .filter(DebcheckIssue.uuid == uuid)
            .one_or_none()
        )
        if not issue:
            abort(404)

        # cache information (as it has to be decoded from json)
        missing = issue.missing
        conflicts = issue.conflicts
        ptype = 'source' if issue.package_type == PackageType.SOURCE else 'binary'

        return render_template(
            'depcheck/issue.html',
            PackageType=PackageType,
            ptype=ptype,
            issue=issue,
            arch_name=', '.join(issue.architectures),
            rss=rss,
            missing=missing,
            conflicts=conflicts,
        )

src/webdash/lkweb/overview/views.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Matthias Klumpp <matthias@tenstral.net>
#
# SPDX-License-Identifier: LGPL-3.0+

from datetime import datetime

import pytz
import humanize
import sqlalchemy
from flask import Blueprint, render_template
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore

from laniakea import LocalConfig
from laniakea.db import (
    Job,
    JobStatus,
    BinaryPackage,
    DebcheckIssue,
    ArchiveRepository,
    ArchiveQueueNewEntry,
    session_scope,
)

from ..extensions import cache

overview = Blueprint('overview', __name__)
g_jobstore = None  # the jobstore can only be loaded once, so we globally cache it


def get_scheduler_jobstore():
    from laniakea.db import Base, Database

    global g_jobstore
    if g_jobstore is None:
        db = Database()
        g_jobstore = SQLAlchemyJobStore(engine=db.engine, tablename='maintenance_jobs', metadata=Base.metadata)
    return g_jobstore


def humanized_job_timediff(job):
    """
    Get time when the job will run next in a human-readable format
    as a string.
    """
    if not job:
        return 'Never'

    timediff = datetime.now(pytz.utc).replace(microsecond=0) - job.next_run_time.astimezone(pytz.utc)
    return humanize.naturaltime(timediff)


@overview.route('/')
@cache.cached(timeout=10)
def index():
    lconf = LocalConfig()
    with session_scope() as session:
        master_repo_id = (
            session.query(ArchiveRepository.id).filter(ArchiveRepository.name == lconf.master_repo_name).one()[0]
        )

        # fetch basic statistics!
        repo_count = session.query(ArchiveRepository.id).count()
        package_count = (
            session.query(BinaryPackage.uuid)
            .filter(BinaryPackage.repo_id == master_repo_id)
            .distinct(BinaryPackage.name)
            .count()
        )
        jobs_pending_count = (
            session.query(Job.uuid)
            .filter(Job.status.in_([JobStatus.WAITING, JobStatus.SCHEDULED, JobStatus.RUNNING]))
            .count()
        )
        debcheck_issues_count = (
            session.query(DebcheckIssue.uuid)
            .filter(DebcheckIssue.repo_id == master_repo_id)
            .distinct(DebcheckIssue.package_name)
            .count()
        )
        review_queue_count = (
            session.query(ArchiveQueueNewEntry.id)
            .filter(
                ArchiveQueueNewEntry.package.has(repo_id=master_repo_id),
            )
            .count()
        )

        # fetch info about scheduled maintenance tasks
        jobstore = get_scheduler_jobstore()
        scheduler_configured = True
        rubicon_nextrun_time = 'disabled'
        publish_nextrun_time = 'disabled'
        spears_nextrun_time = 'disabled'
        debcheck_nextrun_time = 'disabled'
        synchrotron_nextrun_time = 'disabled'
        expire_nextrun_time = 'disabled'
        try:
            job = jobstore.lookup_job('rubicon')
        except sqlalchemy.exc.ProgrammingError:
            # the jobs table likely hasn't been created yet, so we will make no further attempts to fetch its data
            scheduler_configured = False
        if scheduler_configured:
            rubicon_nextrun_time = humanized_job_timediff(job)
            job = jobstore.lookup_job('publish-repos')
            publish_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('expire-repos')
            expire_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('spears-migrate')
            spears_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('debcheck')
            debcheck_nextrun_time = humanized_job_timediff(job)

            job = jobstore.lookup_job('synchrotron-autosync')
            synchrotron_nextrun_time = humanized_job_timediff(job)

        return render_template(
            'index.html',
            repo_count=repo_count,
            package_count=package_count,
            review_queue_count=review_queue_count,
            jobs_pending_count=jobs_pending_count,
            debcheck_issues_count=debcheck_issues_count,
            rubicon_nextrun_time=rubicon_nextrun_time,
            publish_nextrun_time=publish_nextrun_time,
            expire_nextrun_time=expire_nextrun_time,
            spears_nextrun_time=spears_nextrun_time,
            debcheck_nextrun_time=debcheck_nextrun_time,
            synchrotron_nextrun_time=synchrotron_nextrun_time,
        )

src/webdash/templates/default/depcheck/index.html
{% extends 'depcheck/layout.html' %}

{% set page_title = 'Dependency Check' %}

{% block body_header %}
<h1 class="title mb-4">Dependency Check</h1>
{% endblock %}

{% block body %}
<div class="column is-10">

<h4 class="subtitle is-4">Suites with Issues</h4>
<div class="columns is-multiline is-mobile">
  {% for info in repo_suites_with_issues %}
    <div class="column is-half">
      <div class="card">
        <header class="card-header">
            <p class="card-header-title">
            <span class="has-text-weight-light">{{info.rss.repo.name}}</span>&nbsp;{{info.rss.suite.name}}
            {% set btn_style = 'btn-secondary' %}
            {% if info.rss.suite.parents %}
              &nbsp;<span class="tag is-light">Child Suite</span>
            {% endif %}
            {% if info.rss.accept_uploads %}
              &nbsp;<span class="tag is-info">Accepts Uploads</span>
            {% endif %}
            {% if info.rss.devel_target %}
              &nbsp;<span class="tag is-primary">Development Target</span>
            {% endif %}
            </p>
        </header>

        <div class="card-content py-2">
            <div class="content">
              {% if info.rss.suite.parents %}
              <p>Overlay for {% for parent in info.rss.suite.parents  %}<em>{{ parent.name }}</em>{%- if not loop.last %}, {% endif %}{% endfor %}</p>
              {% endif %}

              {% set bin_issue_num_style = 'color:red;' if info.bin_issues_count > 80 else '' %}
              {% set src_issue_num_style = 'color:red;' if info.src_issues_count > 80 else '' %}

              <span class="fa-solid fa-dumpster-fire" style="text-align:right;width:20px;"></span>
                <b style="{{bin_issue_num_style}}">{{info.bin_issues_count}}</b> broken binary packages<br/>
              <span class="fa-solid fa-puzzle-piece" style="text-align:right;width:20px;"></span>
                <b style="{{src_issue_num_style}}">{{info.src_issues_count}}</b> not buildable source packages
            </div>
        </div>
        <footer class="card-footer">
            <a href="{{ url_for('depcheck.issue_list', repo_name=info.rss.repo.name, suite_name=info.rss.suite.name, ptype='binary', arch_name=info.rss.suite.primary_architecture.name, page=1) }}"
               class="card-footer-item">Binary Package Issues</a>
            <a href="{{ url_for('depcheck.issue_list', repo_name=info.rss.repo.name, suite_name=info.rss.suite.name, ptype='source', arch_name=info.rss.suite.primary_architecture.name, page=1) }}"
               class="card-footer-item">Source Package Issues</a>
        </footer>
      </div>
    </div>
  {% endfor %}
</div>

{% if repo_suites_good %}
<h4 class="subtitle is-4 mt-4">Suites without Dependency Issues</h4>
<div class="columns is-multiline is-mobile">
  {% for info in repo_suites_good %}
    <div class="column is-half">

      <div class="card">
        <header class="card-header">
            <p class="card-header-title">
            <span class="has-text-weight-light">{{info.rss.repo.name}}</span>&nbsp;{{info.rss.suite.name}}
            {% set btn_style = 'btn-secondary' %}
            {% if info.rss.suite.parents %}
              &nbsp;<span class="tag is-light">Child Suite</span>
            {% endif %}
            {% if info.rss.accept_uploads %}
              &nbsp;<span class="tag is-info">Accepts Uploads</span>
            {% endif %}
            {% if info.rss.devel_target %}
              &nbsp;<span class="tag is-primary">Development Target</span>
            {% endif %}
            </p>
        </header>
        {% if info.rss.suite.parents %}
        <div class="card-content py-2">
            <div class="content">
              Overlay for {% for parent in info.rss.suite.parents  %}<em>{{ parent.name }}</em>{%- if not loop.last %}, {% endif %}{% endfor %}
            </div>
        </div>
        {% endif %}
      </div>

    </div>
  {% endfor %}
</div>
{% endif %}

</div>
{% endblock %}

src/webdash/templates/default/depcheck/issue.html
{% extends 'depcheck/layout.html' %}

{% set page_title = 'Dependency issues for ' + issue.package_name + ' ' + issue.package_version %}

{% block body_header %}
<h1 class="title">Issue details for {{'binary' if issue.package_type == PackageType.BINARY else 'source'}} {{issue.package_name}}/{{issue.package_version}}</h1>
<h2 class="subtitle is-4">in {{rss.repo.name}}/{{rss.suite.name}} <small><span class="text-secondary"><i class="fas fa-microchip"></i> {{issue.architectures|join(', ')}}</span></small></h2>
{% endblock %}

{% block body %}

<div class="columns is-mobile">
    <div class="column is-6">

        {% if missing %}
        <div class="card">
        <header class="card-header">
            <p class="card-header-title">
            Missing dependencies
            </p>
            <div class="card-header-icon">
            <span class="icon">
                <i class="fas fa-question" aria-hidden="true"></i>
            </span>
            </div>
        </header>
        <div class="card-content py-3">
            <div class="content">
                <ul>
                    {% for m in missing %}
                    <li>
                    <h5 class="subtitle mb-1">{{m.unsat_dependency}}</h5>
                    <p class="mb-1"><b>Required by:</b> {{m.package_name}}<br/>
                    {% if m.package_version %}<b>Version:</b> {{m.package_version}}<br/>{% endif %}

                    {% if m.package_type == PackageType.SOURCE %}
                    <b>Type:</b> <i class="fas fa-drafting-compass"></i> Source Package<br/>
                    {% elif m.package_type == PackageType.BINARY %}
                    <b>Type:</b> <i class="fas fa-cube"></i> Binary Package<br/>
                    {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        </div>
        {% endif %}

        {% if conflicts %}
        <div class="card">
        <header class="card-header">
            <p class="card-header-title">
            Conflicts in the dependency chain
            </p>
            <div class="card-header-icon">
            <span class="icon">
                <i class="fas fa-bomb" aria-hidden="true"></i>
            </span>
            </div>
        </header>
        <div class="card-content py-3">
            <div class="content">
                {% for c in conflicts %}
                    <h4 class="subtitle mb-3">{{c.pkg1.package_name}} <span class="has-text-weight-light">vs.</span> {{c.pkg2.package_name}}</h4>
                    <div class="card has-background-white-ter">
                        <div class="card-content">

                        {% set pkg1_type_html = '' %}
                        {% if c.pkg1.package_type == PackageType.SOURCE %}
                        {% set pkg1_type_html = '<i class="fas fa-drafting-compass"></i>' %}
                        {% elif c.pkg1.package_type == PackageType.BINARY %}
                        {% set pkg1_type_html = '<i class="fas fa-cube"></i>' %}
                        {% endif %}

                        {% set pkg2_type_html = '' %}
                        {% if c.pkg2.package_type == PackageType.SOURCE %}
                        {% set pkg2_type_html = '<i class="fas fa-drafting-compass"></i>' %}
                        {% elif c.pkg2.package_type == PackageType.BINARY %}
                        {% set pkg2_type_html = '<i class="fas fa-cube"></i>' %}
                        {% endif %}

                        <!-- Package 1-->
                        <h5 class="subtitle mb-2">Package 1: {{c.pkg1.package_name}} {{c.pkg1.package_version}}&nbsp;&nbsp;{{ pkg1_type_html | safe }}</h5>
                        {% if c.pkg1.unsat_conflict %}
                        <span><b>Conflict:</b> {{c.pkg1.unsat_conflict}}</span>
                        {% endif %}

                        <ul class="mt-1">
                        {% for d in c.depchain1 %}
                            <li>
                                <b>{{d.package_name}} {{d.package_version}}</b> {% if d.package_type == PackageType.SOURCE %}<small><i class="fas fa-drafting-compass"></i></small>{% endif %}<br/>
                                <p class="mb-1 text-secondary"><b>Depends:</b> {{d.depends}}</p>
                            </li>
                        {% endfor %}
                        </ul>

                        <!-- Package 2-->
                        <h5 class="subtitle mb-2">Package 2: {{c.pkg2.package_name}} {{c.pkg2.package_version}}&nbsp;&nbsp;{{ pkg2_type_html | safe }}</h5>
                        {% if c.pkg2.unsat_conflict %}
                        <span><b>Conflict:</b> {{c.pkg2.unsat_conflict}}</span>
                        {% endif %}

                        <ul class="mt-1">
                        {% for d in c.depchain2 %}
                            <li>
                                <b>{{d.package_name}} {{d.package_version}}</b> {% if d.package_type == PackageType.SOURCE %}<small><i class="fas fa-drafting-compass"></i></small>{% endif %}<br/>
                                <p class="mb-1 text-secondary"><b>Depends:</b> {{d.depends}}</p>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

src/webdash/templates/default/depcheck/issues_list.html
{% extends 'depcheck/layout.html' %}

{% if ptype == 'source' %}
  {% set page_title = 'Dependency issues for {}:{} (source, {})'.format(rss.repo.name, rss.suite.name, arch_name) %}
{% else %}
  {% set page_title = 'Dependency issues for {}:{} (binary, {})'.format(rss.repo.name, rss.suite.name, arch_name) %}
{% endif %}

{% block body_header %}
<h1 class="title mb-4">Dependency issues for {{'source' if ptype == 'source' else 'binary'}} packages in {{rss.repo.name}}/{{rss.suite.name}} [{{arch_name}}]</h1>
{% endblock %}

{% block js_pre %}
{% if current_page <= 1 %}
<script src="{{ url_for('static', filename='js/moment/moment.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/chart/chart.umd.js') }}"></script>
<script src="{{ url_for('static', filename='js/chart/chartjs-adapter-moment.min.js') }}"></script>
{% endif %}
{% endblock %}

{% block body %}

<div class="tabs is-toggle mb-1">
  <ul>
    <li class="{{'is-active' if ptype != 'source'}}">
        <a href="{{ url_for('depcheck.issue_list', repo_name=rss.repo.name, suite_name=rss.suite.name, ptype='binary', arch_name=rss.suite.primary_architecture.name, page=1) if ptype == 'source' else '#'}}">
            <span class="icon is-small"><i class="fas fa-cube" aria-hidden="true"></i></span>
            <span>Binary Packages</span>
        </a>
    </li>
    <li class="{{'is-active' if ptype == 'source'}}">
        <a href="{{ url_for('depcheck.issue_list', repo_name=rss.repo.name, suite_name=rss.suite.name, ptype='source', arch_name=rss.suite.primary_architecture.name, page=1) if ptype != 'source' else '#'}}">
            <span class="icon is-small"><i class="fas fa-drafting-compass" aria-hidden="true"></i></span>
            <span>Source Packages</span>
        </a>
    </li>
  </ul>
</div>

<div class="column is-8">

    <div class="dropdown mb-3 is-hoverable">
        <div class="dropdown-trigger">
            <button class="button" aria-haspopup="true" aria-controls="archs-menu">
            <span>Architecture</span>
            <span class="icon is-small">
                <i class="fas fa-angle-down" aria-hidden="true"></i>
            </span>
            </button>
        </div>
        <div class="dropdown-menu" id="archs-menu" role="menu">
            <div class="dropdown-content">
                {% for arch in rss.suite.architectures %}
                <a class="dropdown-item" href="{{ url_for('depcheck.issue_list', repo_name=rss.repo.name, suite_name=rss.suite.name, ptype=ptype, arch_name=arch.name, page=1) }}">
                    <i class="fas fa-microchip"></i> {{arch.name}}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if current_page <= 1 %}
    <canvas id="issueChart" style="width:100%;max-height:140px"></canvas>

    <script>
      const data = JSON.parse('{{stats_raw|safe}}').map(item => {
        return {
          x: new Date(item.x * 1000),
          y: item.y
        };
      });

      new Chart('issueChart', {
        type: 'line',
        data: {
          datasets: [{
              data: data,
              label: 'Issues for {{ptype}} packages in {{arch_name}}',
              fill: true
            }]
        },
        options: {
            scales: {
              x: {
                type: 'time',
                time: {
                    unit: 'month',
                    displayFormats: {
                     day: 'YYYY-MM',
                  }
                }
              }
            },
            plugins: {
              legend: {
                  display: false
              }
            }
          }
      });
    </script>
    {% endif %}

    {% for issue in issues %}
        <div class="card">
        <header class="card-header">
            <div class="card-header-title has-text-weight-semibold">
                <a href="{{ url_for('depcheck.issue_details', repo_name=rss.repo.name, suite_name=rss.suite.name, uuid=issue.uuid) }}">
                    <span class="has-text-black">{{issue.package_name}} {{issue.package_version}}</span>&nbsp;
                    <p class="mb-1 text-secondary"><i class="fas fa-microchip"></i> {{issue.architectures|join(', ')}}</p>
                    {% for missing in issue.missing %}
                    <p class="mb-1"><i class="far fa-question-circle"></i> {{missing.unsat_dependency}}</p>
                    {% endfor %}
                    {% for conflict in issue.conflicts %}
                    <p class="mb-1"><i class="fas fa-fist-raised"></i></i> {{conflict.pkg1.package_name}} vs. {{conflict.pkg2.package_name}}</p>
                    {% endfor %}
                </a>
            </div>
        </header>
        </div>
    {% endfor %}

    <br/>
    <nav class="pagination" role="navigation" aria-label="pagination">
        <a class="pagination-previous"
            href="{{ url_for('depcheck.issue_list', repo_name=rss.repo.name, suite_name=rss.suite.name, ptype=ptype, arch_name=arch_name, page=current_page-1) if current_page > 1 else '#'}}"
            {{'disabled' if current_page <= 1 }}>
            Previous
        </a>
        <a class="pagination-next"
            href="{{ url_for('depcheck.issue_list', repo_name=rss.repo.name, suite_name=rss.suite.name, ptype=ptype, arch_name=arch_name, page=current_page+1) if current_page < page_count else '#'}}"
            {{'disabled' if current_page >= page_count }}>
            Next
        </a>

        <ul class="pagination-list">

        {% for i in range(1, page_count + 1) %}
            <li>
                <a class="pagination-link {{'is-current' if i == current_page }}" aria-label="Goto page {{i}}"
                    href="{{ url_for('depcheck.issue_list', repo_name=rss.repo.name, suite_name=rss.suite.name, ptype=ptype, arch_name=arch_name, page=i) }}">{{i}}</a>
            </li>
        {% endfor %}
        </ul>
    </nav>
</div>
{% endblock %}

src/webdash/templates/default/depcheck/layout.html
{% extends 'layouts/base.html' %}

{% set active_menu = 'depcheck' %}

{% block breadcrumbs %}
<ul>
    <li>
        <a href="{{ url_for('overview.index') }}">Home</a>
    </li>
    <li class="{{'is-active' if suites }}">
        <a href="{{ url_for('depcheck.index') }}">DepCheck</a>
    </li>
    {% if suite %}
    <li class="{{'is-active' if not issue}}">
        <a href="{{ url_for('depcheck.issue_list',
                    repo_name=rss.repo.name, suite_name=rss.suite.name, ptype=ptype, arch_name=arch_name, page=1) }}">{{rss.repo.name}}:{{rss.suite.name}} [{{arch_name}}] - {{ptype}}</a>
    </li>
    {% endif %}
    {% if issue %}
    <li class="is-active"><p>{{issue.package_name}} - {{issue.package_version}}</p></li>
    {% endif %}
</ul>
{% endblock %}